# Generated by Django 5.1.6 on 2025-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDomainsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('domain', models.CharField(max_length=100)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'user_domains_history',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='user_domain_user_id_8af0a1_idx'), models.Index(fields=['user_id', 'domain', 'created_at'], name='user_domain_user_id_1a4ca2_idx')],
                'unique_together': {('user_id', 'domain', 'created_at')},
            },
        ),
    ]
